spring:
  application:
    name: ds-commerce

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # ou 'create', 'create-drop', 'none', dependendo do seu uso
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
